#!/bin/bash

GP_VERSION=4.3.11.1MS31

GP_BUILDNUMBER=1
if [ -f BUILD_NUMBER ] ; then
    GP_BUILDNUMBER=`cat BUILD_NUMBER`
fi

FLAG="${1:-noflag}"
if [ "$FLAG" = '--short' ] ; then
    echo "${GP_VERSION}"
else
    echo "${GP_VERSION} build ${GP_BUILDNUMBER}"
fi
