#!/bin/bash

GP_VERSION=4.3.6.3

# Pickup environment variable for suffix.
# This allows team branches to look like a special build.
if [ -n "${GP_VERSION_SUFFIX}" ] ; then
    GP_VERSION=${GP_VERSION}${GP_VERSION_SUFFIX}
fi

GP_BUILDNUMBER=dev
if [ -f BUILD_NUMBER ] ; then
    GP_BUILDNUMBER=`cat BUILD_NUMBER`
fi
if [ -f BUILD_EDITION ] ; then
    GP_BUILDEDITION=" `cat BUILD_EDITION`"
fi

echo "${GP_VERSION} build ${GP_BUILDNUMBER}${GP_BUILDEDITION}"

exit 0
