GPMGMT_SRC=$(CURDIR)
PYLIB_SRC=$(GPMGMT_SRC)/bin/pythonSrc
PYTHONSRC_INSTALL=$(PYLIB_SRC)/install
BEHAVE_DIR=behave-$(BEHAVE_VERSION)
BEHAVE_BIN=$(PYTHONSRC_INSTALL)/bin/behave
PYTHONSRC_INSTALL_SITE=$(PYLIB_SRC)/install/lib/python2.6/site-packages
PYTHONSRC_INSTALL_PYTHON_PATH=$(PYTHONPATH):$(PYTHONSRC_INSTALL_SITE)

$(BEHAVE_BIN):
	make -C bin $(BEHAVE_BIN)

# To pass in custom flags as behave args(such as multiple flags),
# use flags=--tags=foo, --tags=-bar
behave: $(BEHAVE_BIN)
	@echo "Running behave on management scripts..."
	@if [ -n """$(flags)""" ]; then \
	        PYTHONPATH=$(PYTHONSRC_INSTALL_PYTHON_PATH):$(GPMGMT_SRC) python $(BEHAVE_BIN) $(GPMGMT_SRC)/test/behave/* -s -k $(flags) 2>&1 ; \
	elif [ -n """$(tags)""" ]; then \
	        PYTHONPATH=$(PYTHONSRC_INSTALL_PYTHON_PATH):$(GPMGMT_SRC) python $(BEHAVE_BIN) $(GPMGMT_SRC)/test/behave/* -s -k --tags=$(tags) 2>&1 ; \
	else \
	        echo "Please specify tags=tagname or flags=[behave flags]"; \
	fi
